image: Visual Studio 2022

version: '0.7_{build}'
shallow_clone: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

configuration: Release

environment:
  matrix:
    - MSYSTEM: MINGW64
      BASH_PATH: C:\msys64\usr\bin\bash
      QT: C:\Qt\6.4\mingw_64

install:
  - set Path=%QT%\bin;%Path%
  - cmd: '%BASH_PATH% -lc "$APPVEYOR_BUILD_FOLDER/ci/appveyor/get-dependencies.sh"'

before_build:
  - cmd: '%BASH_PATH% -lc "$APPVEYOR_BUILD_FOLDER/ci/appveyor/configure.sh"'

build_script:
  - cmd: '%BASH_PATH% -lc "$APPVEYOR_BUILD_FOLDER/ci/appveyor/build.sh"'

after_build:
  - cmd: '%BASH_PATH% -lc "$APPVEYOR_BUILD_FOLDER/ci/appveyor/package.sh"'

test_script:
  - cmd: '%BASH_PATH% -lc "$APPVEYOR_BUILD_FOLDER/ci/appveyor/run-tests.sh"'
