image: Visual Studio 2015

shallow_clone: true
clone_depth: 1

configuration: Release

environment:
  matrix:
    - MSYSTEM: MINGW32
      BASH_PATH: C:\msys64\usr\bin\bash 
      QT5: C:\Qt\5.11.1\mingw53_32

install:
#  - appveyor AddMessage "Installing hunspell" -Category Information
  - set Path=%QT5%\bin;%Path%
  - cmd: '%BASH_PATH% -lc "$APPVEYOR_BUILD_FOLDER/ci/appveyor/get-dependencies.sh"'

before_build:
#  - # run cmake

build_script:
  - echo build_script

test_script:
  - echo This is my custom test script

before_deploy:


