name: 'Package TeXworks for Windows'
author: 'Stefan Löffler'
description: ''

inputs:
  builddir:
    description: 'Directory the program was built in (default: build)'
    required: false
    default: build

outputs:
  file:
    description: 'The filename of the packaged artifact (relative to builddir)'
    value: ${{ steps.info.outputs.file }}
  version:
    description: 'The version of the packaged artifact (e.g., 0.7)'
    value: ${{ steps.info.outputs.version }}
  fullversion:
    description: 'The full version of the packaged artifact (e.g., 0.7-202011160643-git_14dcc2c)'
    value: ${{ steps.info.outputs.fullversion }}

runs:
  using: composite
  steps:
    - name: Assemble package
      shell: wsl-bash {0}
      run: cpack --verbose
      working-directory: ${{ inputs.builddir }}

    - name: Info
      shell: wsl-bash {0}
      id: info
      run: |
        GITHUB_OUTPUT=$(echo "${{ github.output }}" | tr '\\' '/' | sed -e 's!\([A-Za-z]\):/!/mnt/\L\1/!')
        FILENAME=$(find ${{ inputs.builddir }} -maxdepth 1 -name 'TeXworks-win-*.zip')
        VERSION=$(basename "$FILENAME" | sed -e 's/^TeXworks-win-\([^-]*\)-.*\.zip$/\1/')
        FULLVERSION=$(basename "$FILENAME" | sed -e 's/^TeXworks-win-\(.*\)\.zip$/\1/')
        echo "MD5"
        md5sum "$FILENAME"
        echo "SHA256"
        sha256sum "$FILENAME"
        echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
        echo "fullversion=${FULLVERSION}" >> "${GITHUB_OUTPUT}"
        echo "file=${FILENAME}" >> "${GITHUB_OUTPUT}"
