name: 'Package TeXworks for macOS'
author: 'Stefan Löffler'
description: ''

inputs:
  builddir:
    description: 'Directory the program was built in (default: build)'
    required: false
    default: build

outputs:
  file:
    description: 'The filename of the packaged artifact (relative to builddir)'
    value: ${{ steps.info.outputs.file }}
  version:
    description: 'The version of the packaged artifact (e.g., 0.7.0)'
    value: ${{ steps.info.outputs.version }}
  fullversion:
    description: 'The full version of the packaged artifact (e.g., 0.7.0-202011160643-git_14dcc2c)'
    value: ${{ steps.info.outputs.fullversion }}

runs:
  using: composite
  steps:
    - name: 'Running CPack'
      shell: bash
      run: cpack --verbose
      working-directory: ${{ inputs.builddir }}
    - name: 'Info'
      id: info
      shell: bash
      run: |
        FILENAME=$(find ${{ inputs.builddir }} -depth 1 -name 'TeXworks-macos-*.dmg')
        VERSION=$(basename "$FILENAME" | sed -e 's/^TeXworks-macos-\([^-]*\)-.*\.dmg$/\1/')
        FULLVERSION=$(basename "$FILENAME" | sed -e 's/^TeXworks-macos-\(.*\)\.dmg$/\1/')
        echo "::set-output name=version::${VERSION}"
        echo "::set-output name=fullversion::${FULLVERSION}"
        echo "::set-output name=file::${FILENAME}"
