name: 'Set up build environment for TeXworks for macOS'
author: 'Stefan Löffler'
description: ''

runs:
  using: composite
  steps:
    - name: Install Homebrew dependencies
      shell: bash
      run: |
        brew update > brew_update.log || { echo "::error::Updating homebrew failed"; cat brew_update.log; exit 1; }
        brew uninstall --ignore-dependencies brotli fontconfig freetype libjpeg libpng libtiff webp zstd
        brew install automake libtool pkg-config

    - name: Build dependencies
      shell: bash
      run: |
        cmake -S "${{ github.action_path }}" -B "${{ github.action_path }}/build" -DCMAKE_INSTALL_PREFIX=${RUNNER_WORKSPACE}/tw-deps
        PKG_CONFIG_PATH=${RUNNER_WORKSPACE}/tw-deps/lib/pkgconfig cmake --build "${{ github.action_path }}/build" -v
